<a href="https://colab.research.google.com/github/mrdbcse/deep-learning-pytorch/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Fri Feb 14 17:00:19 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P0             48W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [ ]:
print("Learning PyTorch")

Learning PyTorch


In [ ]:
!pip3 uninstall --yes torch torchaudio torchvision torchtext torchdata

In [ ]:
!pip3 install torch torchaudio torchvision torchtext torchdata

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 85.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 39.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 95.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 80.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12


In [ ]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device.type


'cuda'

In [ ]:
import torch

print(torch.__version__)

2.5.1+cu124


### Tensors

In [1]:
#  -----------------------Tensors---------------------
import torch

# ------------------- scalar ---------------

scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())


# ------------------- vector ---------------


vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

# ------------------ matrix --------------------

matrix = torch.tensor([[7,8],[9,10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[0][1])
print(matrix[1][0])

# ------------------ tensor --------------------

tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0][0][1])



------------------- scalar ---------------
tensor(7)
0
7
------------------- vector ---------------
tensor([7, 7])
1
torch.Size([2])
------------------ matrix --------------------
tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor(8)
tensor(9)
------------------ tensor --------------------
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor(2)


### Random Tensors

In [2]:
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.8794, 0.8512, 0.4315, 0.9575],
        [0.9425, 0.9947, 0.0878, 0.3132],
        [0.8482, 0.9876, 0.7078, 0.3423]])
2
torch.Size([3, 4])


In [23]:
random_image_size_tensor = torch.rand(size=(224,224,3)) ### height, width, colour channels
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

tensor([[[1.0057e-01, 9.4350e-02, 6.5886e-01],
         [1.1347e-01, 5.4693e-01, 7.4396e-01],
         [7.1559e-01, 7.8833e-01, 3.4640e-01],
         ...,
         [2.0538e-01, 5.1139e-01, 8.9047e-01],
         [8.9965e-01, 9.0255e-01, 4.1946e-01],
         [2.8908e-01, 1.0609e-01, 6.8774e-01]],

        [[4.9733e-01, 7.2923e-01, 8.2558e-01],
         [8.9815e-01, 7.2630e-01, 2.7595e-01],
         [9.0956e-01, 4.6738e-01, 3.2471e-01],
         ...,
         [9.1554e-01, 2.1126e-01, 2.6997e-01],
         [6.3591e-01, 9.1381e-01, 3.0027e-01],
         [8.2387e-01, 5.7666e-01, 5.0236e-01]],

        [[5.0413e-01, 3.5396e-01, 1.6093e-01],
         [5.9479e-04, 1.4588e-01, 4.2962e-01],
         [3.8580e-01, 3.4748e-01, 9.8126e-03],
         ...,
         [3.5364e-01, 8.0333e-01, 6.9114e-01],
         [2.1256e-01, 4.2593e-01, 3.3944e-02],
         [9.3894e-01, 6.2778e-01, 4.8160e-01]],

        ...,

        [[3.8408e-01, 7.1922e-01, 5.0482e-01],
         [7.3283e-01, 4.8301e-01, 4.8263e-01]

In [7]:
zero=torch.zeros(size=(3,4))
print(zero)
print(zero.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [5]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
one=torch.ones(size=(3,4))
print(one)
print(one.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [17]:
# range of tensors

range_tensors=torch.arange(start=0,end=101,step=10)

In [18]:
# creating tensors like

ten_zeros = torch.zeros_like(input=range_tensors)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [22]:
# tensor data types
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [21]:
float_16_tensor=float_32_tensor.type(torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [24]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
print(int_32_tensor)
print(int_32_tensor.dtype)

tensor([3, 6, 9], dtype=torch.int32)
torch.int32


In [26]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [27]:
# find out details about tensors

random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.dtype)
print(random_tensor.shape)
print(random_tensor.device)

tensor([[0.1950, 0.2895, 0.8884, 0.9062],
        [0.8927, 0.4247, 0.7139, 0.7026],
        [0.9266, 0.4034, 0.9265, 0.9936]])
torch.float32
torch.Size([3, 4])
cpu


In [40]:
# tensor operations: addition, substraction, multiplication, division, matrix multiplication

tensor = torch.tensor([1,2,3])
print(f"Addition: {tensor + 10}")
print(f"Substraction: {tensor - 1}")
print(f"Multiplication: {tensor * 2}")
print(f"Division: {tensor / 2}")

# matrix multiplication (dot product)

print(tensor * tensor)
print(tensor.matmul(tensor))

torch.matmul(torch.rand(3,10),torch.rand(10,3))



Addition: tensor([11, 12, 13])
Substraction: tensor([0, 1, 2])
Multiplication: tensor([2, 4, 6])
Division: tensor([0.5000, 1.0000, 1.5000])
tensor([1, 4, 9])
tensor(14)


tensor([[1.6671, 1.8327, 1.1321],
        [2.7721, 2.6454, 1.1017],
        [3.4309, 3.5116, 2.1519]])

In [55]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])
tensor_b = torch.tensor([[7,10],[8,11],[9,12]])
print("Tensor A: \n",tensor_a)
print("Tensor B: \n",tensor_b)

print("Tensor A Shape: \n",tensor_a.shape)
print("Tensor B Shape: \n", tensor_b.shape)

# matrix transpose
print("Tensor B Transpose: \n",tensor_b.T)
print("Tesnsor B Transpose Shape:\n ",tensor_b.T.shape)

print("Multiplication Output: \n",torch.mm(tensor_a,tensor_b.T))
print("Multiplication Output Shape: \n",torch.mm(tensor_a,tensor_b.T).shape)


Tensor A: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor B: 
 tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
Tensor A Shape: 
 torch.Size([3, 2])
Tensor B Shape: 
 torch.Size([3, 2])
Tensor B Transpose: 
 tensor([[ 7,  8,  9],
        [10, 11, 12]])
Tesnsor B Transpose Shape:
  torch.Size([2, 3])
Multiplication Output: 
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Multiplication Output Shape: 
 torch.Size([3, 3])
