<a href="https://colab.research.google.com/github/mrdbcse/deep-learning-pytorch/blob/master/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Fundamentals
Link: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!nvidia-smi

Fri Feb 14 17:00:19 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P0             48W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

### PyTorch Installation

In [ ]:
!pip3 uninstall --yes torch torchaudio torchvision torchtext torchdata

In [ ]:
!pip3 install torch torchaudio torchvision torchtext torchdata

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 85.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 39.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 95.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 80.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12


In [ ]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device.type


'cuda'

In [ ]:
import torch

print(torch.__version__)

2.5.1+cu124


### Tensors
1. Scalar
2. Vector
3. Matrix

In [ ]:
#  -----------------------Tensors---------------------
import torch

# ------------------- scalar ---------------

scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())


# ------------------- vector ---------------


vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

# ------------------ matrix --------------------

matrix = torch.tensor([[7,8],[9,10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix[0][1])
print(matrix[1][0])

# ------------------ tensor --------------------

tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor[0][0][1])



------------------- scalar ---------------
tensor(7)
0
7
------------------- vector ---------------
tensor([7, 7])
1
torch.Size([2])
------------------ matrix --------------------
tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor(8)
tensor(9)
------------------ tensor --------------------
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor(2)


### Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.8794, 0.8512, 0.4315, 0.9575],
        [0.9425, 0.9947, 0.0878, 0.3132],
        [0.8482, 0.9876, 0.7078, 0.3423]])
2
torch.Size([3, 4])


In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3)) ### height, width, colour channels
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

tensor([[[1.0057e-01, 9.4350e-02, 6.5886e-01],
         [1.1347e-01, 5.4693e-01, 7.4396e-01],
         [7.1559e-01, 7.8833e-01, 3.4640e-01],
         ...,
         [2.0538e-01, 5.1139e-01, 8.9047e-01],
         [8.9965e-01, 9.0255e-01, 4.1946e-01],
         [2.8908e-01, 1.0609e-01, 6.8774e-01]],

        [[4.9733e-01, 7.2923e-01, 8.2558e-01],
         [8.9815e-01, 7.2630e-01, 2.7595e-01],
         [9.0956e-01, 4.6738e-01, 3.2471e-01],
         ...,
         [9.1554e-01, 2.1126e-01, 2.6997e-01],
         [6.3591e-01, 9.1381e-01, 3.0027e-01],
         [8.2387e-01, 5.7666e-01, 5.0236e-01]],

        [[5.0413e-01, 3.5396e-01, 1.6093e-01],
         [5.9479e-04, 1.4588e-01, 4.2962e-01],
         [3.8580e-01, 3.4748e-01, 9.8126e-03],
         ...,
         [3.5364e-01, 8.0333e-01, 6.9114e-01],
         [2.1256e-01, 4.2593e-01, 3.3944e-02],
         [9.3894e-01, 6.2778e-01, 4.8160e-01]],

        ...,

        [[3.8408e-01, 7.1922e-01, 5.0482e-01],
         [7.3283e-01, 4.8301e-01, 4.8263e-01]

### Zeros and Ones Tensors
* Zeros: `0`
* Ones: `1`

In [ ]:
zero = torch.zeros(size=(3,4))
print(zero)
print(zero.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [ ]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(size=(3,4))
print(one)
print(one.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


### Range of Tensors

In [ ]:
# range of tensors

range_tensors=torch.arange(start=0,end=101,step=10)

In [ ]:
# creating tensors like

ten_zeros = torch.zeros_like(input=range_tensors)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor data types

In [ ]:
# tensor data types
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
print(int_32_tensor)
print(int_32_tensor.dtype)

tensor([3, 6, 9], dtype=torch.int32)
torch.int32


In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Details about Tensor

In [ ]:
# find out details about tensors

random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.dtype)
print(random_tensor.shape)
print(random_tensor.device)

tensor([[0.1950, 0.2895, 0.8884, 0.9062],
        [0.8927, 0.4247, 0.7139, 0.7026],
        [0.9266, 0.4034, 0.9265, 0.9936]])
torch.float32
torch.Size([3, 4])
cpu


### Tensor Operations
1. Addition
2. Substraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [ ]:
# tensor operations: addition, substraction, multiplication, division, matrix multiplication

tensor = torch.tensor([1,2,3])
print(f"Addition: {tensor + 10}")
print(f"Substraction: {tensor - 1}")
print(f"Multiplication: {tensor * 2}")
print(f"Division: {tensor / 2}")

# matrix multiplication (dot product)

print(tensor * tensor)
print(tensor.matmul(tensor))

torch.matmul(torch.rand(3,10),torch.rand(10,3))



Addition: tensor([11, 12, 13])
Substraction: tensor([0, 1, 2])
Multiplication: tensor([2, 4, 6])
Division: tensor([0.5000, 1.0000, 1.5000])
tensor([1, 4, 9])
tensor(14)


tensor([[1.6671, 1.8327, 1.1321],
        [2.7721, 2.6454, 1.1017],
        [3.4309, 3.5116, 2.1519]])

In [ ]:
tensor_a = torch.tensor([[1,2],[3,4],[5,6]])
tensor_b = torch.tensor([[7,10],[8,11],[9,12]])
print("Tensor A: \n",tensor_a)
print("Tensor B: \n",tensor_b)

print("Tensor A Shape: \n",tensor_a.shape)
print("Tensor B Shape: \n", tensor_b.shape)

# matrix transpose
print("Tensor B Transpose: \n",tensor_b.T)
print("Tesnsor B Transpose Shape:\n ",tensor_b.T.shape)

print("Multiplication Output: \n",torch.mm(tensor_a,tensor_b.T))
print("Multiplication Output Shape: \n",torch.mm(tensor_a,tensor_b.T).shape)


Tensor A: 
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor B: 
 tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
Tensor A Shape: 
 torch.Size([3, 2])
Tensor B Shape: 
 torch.Size([3, 2])
Tensor B Transpose: 
 tensor([[ 7,  8,  9],
        [10, 11, 12]])
Tesnsor B Transpose Shape:
  torch.Size([2, 3])
Multiplication Output: 
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Multiplication Output Shape: 
 torch.Size([3, 3])


### Tensor aggregation

In [ ]:
# Tensor aggregation

x = torch.arange(1,100,7)
print(x)
print("Minimum: ", x.min())
print("Maximum: ", x.max())
print("Mean: ", x.type(torch.float32).mean())
print("Sum: ",x.sum())

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])
Minimum:  tensor(1)
Maximum:  tensor(99)
Mean:  tensor(50.)
Sum:  tensor(750)


### Positional Minimum and Maximum

In [ ]:
# Positional min and max

print("Tensor: ",x)

print("Positional Minimum: ",x.argmin())
print("Positional Maximum: ",x.argmax())

Tensor:  tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])
Positional Minimum:  tensor(0)
Positional Maximum:  tensor(14)


### Reshaping, Viewing, Squeeezing, Unsqueezing and Stacking Tensors

In [ ]:
import torch
x = torch.arange(1.,10.)
print(x, x.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [ ]:
# adding an extra dimension

x_reshaped = x.reshape(1,9)
print(x_reshaped, x_reshaped.shape)
x_reshaped = x.reshape(9,1)
print(x_reshaped, x_reshaped.shape)


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


In [ ]:
# changeing the view

y = x.view(1,9)
print(y, y.shape)

y[:,0] = 3
print(y, x)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]]) tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# stack tensor on the top of each other

x_stacked = torch.stack([x,x,x,x],dim=0)
print(x_stacked)

y_stacked = torch.stack([x,x,x,x],dim=1)
print(y_stacked)

tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.],
        [3., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[3., 3., 3., 3.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [ ]:
# squeezing a tensor

x_reshaped = x.reshape(1,9)
print("Previous Tensor: ",x_reshaped,"\nPrevious Shape: ", x_reshaped.shape)

x_squeezed = x_reshaped.squeeze()
print("Squeezed Tensor: ",x_squeezed,"\nSqueezed Shape:", x_squeezed.shape)

Previous Tensor:  tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Previous Shape:  torch.Size([1, 9])
Squeezed Tensor:  tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.]) 
Squeezed Shape: torch.Size([9])


In [ ]:
# unsqueezing a tensor

print("Previous Tensor: ",x_squeezed,"\nPrevious Shape: ", x_squeezed.shape)

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print("Unsqueezed Tensor: ",x_unsqueezed,"\nUnsqueezed Shape:", x_unsqueezed.shape)

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print("Unsqueezed Tensor: ",x_unsqueezed,"\nUnsqueezed Shape:", x_unsqueezed.shape)

Previous Tensor:  tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.]) 
Previous Shape:  torch.Size([9])
Unsqueezed Tensor:  tensor([[3., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Unsqueezed Shape: torch.Size([1, 9])
Unsqueezed Tensor:  tensor([[3.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) 
Unsqueezed Shape: torch.Size([9, 1])


### Permuting a Tensor

In [ ]:
# permuting a tensor

x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)
print(x_original.shape)
print(x_permuted.shape)
print(x_original[0,0,0])
print(x_permuted[0,0,0])

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])
tensor(0.8457)
tensor(0.8457)


### Selecting data from tensors (indexing)

In [ ]:
# create a tensor

import torch

x = torch.arange(1,10).reshape(1,3,3)
print(x, x.shape)
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[0][1][1])
print(x[0][2][2])
print(x[:,0])
print(x[:,:,1])
print(x[:,1,1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(5)
tensor(9)
tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])


### PyTorch tensors and NumPy

In [ ]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(array, array.dtype)
print(tensor, tensor.dtype)

[1. 2. 3. 4. 5. 6. 7.] float64
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) torch.float64


In [ ]:
# change the value of array

array += 1
print(array, array.dtype)
print(tensor, tensor.dtype)

[2. 3. 4. 5. 6. 7. 8.] float64
tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64) torch.float64


In [ ]:
# tensor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor, tensor.dtype)
print(numpy_tensor, numpy_tensor.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.]) torch.float32
[1. 1. 1. 1. 1. 1. 1.] float32


In [ ]:
# change the value of tensor

tensor += 1
print(tensor, tensor.dtype)
print(numpy_tensor, numpy_tensor.dtype)

tensor([2., 2., 2., 2., 2., 2., 2.]) torch.float32
[2. 2. 2. 2. 2. 2. 2.] float32


### PyTorch Reproducibility

In [ ]:
# creating two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3511, 0.8650, 0.6631, 0.7868],
        [0.0661, 0.9351, 0.5158, 0.0199],
        [0.7709, 0.9698, 0.6839, 0.3402]])
tensor([[0.8692, 0.5501, 0.5928, 0.1305],
        [0.4752, 0.8511, 0.0763, 0.5196],
        [0.1711, 0.5042, 0.2348, 0.7692]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random seed

import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Check for GPU access in PyTorch

In [ ]:
!nvidia-smi

Tue Feb 18 16:08:20 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   31C    P0             45W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [ ]:
import torch

torch.cuda.is_available()



True

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of gpus

torch.cuda.device_count()

1

In [ ]:
# putting tensors and models on the GPU

tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [ ]:
# tensor back on cpu

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])